services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: cinema_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 127.0.0.1:8000"
    volumes:
      - .:/cinema
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=cinema_db
      - DB_USER=cinema_user
      - DB_PASSWORD=cinema_pass
      - DB_HOST=db

volumes:
  mysql_data:
