# Generated by Django 5.2.1 on 2025-05-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='staus',
            new_name='status',
        ),
    ]
